### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by iskunk**
This covers most of the aspects I wanted to see addressed.

The one remaining item was the chattiness of the logging---I would reduce it so that the common case (no new updates found) produces one entry at most. Does that sound good to you?

### CODE REVIEW

**Comment by iskunk** [comment]
Added a couple tweaks I missed earlier:

* Have the script live under `/var/local/` instead of `/opt/`, since the latter is typically meant to be read-only. (Hope this is okay? I don't want to go all-out and have the script and state live separately, but after writing enough AppArmor rules, treating `/opt` as writable rubbed me the wrong way)

* Adjust the check to be every 17 minutes instead of 15, so that it doesn't run at fixed times every hour (before the randomized delay is added).

**Comment by Kangie** [comment]
LGTM. We can reduce the logs too - no problem there.

**Comment by iskunk** [comment]
All right, a few remaining tweaks here:

* Change some (common-case) log messages to `debug` priority, and filter them out by default in the `log()` function

* Add error check and timeout to the `curl` call

* Add version info to some log messages

* Use `cmp -s` instead of `diff -q`

* Move `Firing repository_dispatch event` message after the token check

**Comment by Kangie** [comment]
New changes seem fine, LGTM.

**Comment by iskunk** [comment]
Thanks, merged!

Please update the system running this when you can. Note the new directory location, and state-file filenames, of course.

**Pull request merged**
